// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDBPath():Promise<string>;

export function GetInfoFromDB(arg1:string):Promise<main.Annotations>;
