// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetInfoFromDB(arg1) {
  return window['go']['main']['App']['GetInfoFromDB'](arg1);
}
